### ISSUE TITLE
OBS_API_initAPI Error

### ISSUE THREAD

**Issue by DavidSongzw** [qlteacher/obs-example#3]
Windows系统 OBS_API_initAPI 初始化在开发模式正常，打包完成后报错，看本地日志是

> `[000:00:00:01.442.190.800][Info] Reset video failed with error: -1
[000:00:00:01.442.221.100][Info] Error returning now`

有遇到过吗

**Comment by gundamff** [comment]
已经离职了 这块东西没再调过 估计得看看obl的log?

**Comment by DavidSongzw** [comment]
找到问题了 打包之后工作区路径和开发时候不同 判断环境设置工作区就行了
