### ISSUE TITLE
如何选中场景资源并产生对应的选择框

### ISSUE THREAD

**Issue by hamburger-l** [qlteacher/obs-example#4]
我在streamlab-obs项目里看到对scene-item的selected设置为true后界面上会有对应的选择框出现，但我同样操作后没有出现，请问对这方面有了解吗？

![1629280143(1)](https://user-images.githubusercontent.com/45661726/129997121-9de8dba4-d199-42cf-9309-d706e2b4fac5.png)

**Comment by flying19880517** [comment]
1、启用drawUI和drawGuideLines
2、setOutputSource应使用transition而不是直接用scene
```JavaScript
  obs.NodeObs.OBS_content_setShouldDrawUI(displayId, true)
  obs.NodeObs.OBS_content_setDrawGuideLines(displayId, true)
  const transition = obs.TransitionFactory.create('cut_transition', 'myTransition', {})
  transition.set(scene)
  obs.Global.setOutputSource(0, transition)
```

**Comment by hamburger-l** [comment]
> 1、启用drawUI和drawGuideLines 2、setOutputSource应使用transition而不是直接用scene
> 
> ```js
>   obs.NodeObs.OBS_content_setShouldDrawUI(displayId, true)
>   obs.NodeObs.OBS_content_setDrawGuideLines(displayId, true)
>   const transition = obs.TransitionFactory.create('cut_transition', 'myTransition', {})
>   transition.set(scene)
>   obs.Global.setOutputSource(0, transition)
> ```

好的谢谢！
